version: '3.8'

services:

  sae-mysql:
    container_name: sae-mysql
    image: mysql:8.0.40
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./sae-data/mysql/mysql-data:/var/lib/mysql
      - ./sae-data/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    networks:
      - sae-network

networks:
  sae-network:
    driver: bridge

volumes:
  mysql-data:
